//User
export const userConstants = {
  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  RESTORE_USER: 'USER_RESTORE_USER',

  POSSITION: 'USER_POSSITION',
  LOGOUT: 'USER_LOGOUT',
};

export const tokenConstants = {
  REGISTER_TOKEN_REQUEST: 'USER_REGISTER_TOKEN_REQUEST',
  REGISTER_TOKEN_SUCCESS: 'USER_REGISTER_TOKEN_SUCCESS',
  REGISTER_TOKEN_FAILURE: 'USER_REGISTER_TOKEN_FAILURE',

  LOGIN_TOKEN_REQUEST: 'USER_LOGIN_TOKEN_REQUEST',
  LOGIN_TOKEN_SUCCESS: 'USER_LOGIN_TOKEN_SUCCESS',
  LOGIN_TOKEN_FAILURE: 'USER_LOGIN_TOKEN_FAILURE',

  RESTORE_TOKEN: 'USER_RESTORE_TOKEN',

  LOGOUT: 'USER_TOKEN_LOGOUT',
};

//Map
export const USE_MAP = 'USE_MAP';

export const mapConstants = {
  POINT_INFORMATION: 'MAP_POINT_INFORMATION',
  SET_NAVIGATION: 'SET_NAVIGATION',
};

export const placeConstants = {
  ACTIVATE_REQUEST: 'ACTIVATE_REQUEST',
  ACTIVATE_SUCCESS: 'ACTIVATE_SUCCESS',
  ACTIVATE_FAILURE: 'ACTIVATE_FAILURE',

  DEACTIVATION_REQUEST: 'DEACTIVATION_REQUEST',
  DEACTIVATION_SUCCESS: 'DEACTIVATION_SUCCESS',
  DEACTIVATION_FAILURE: 'DEACTIVATION_FAILURE',

  BOOKING_REQUEST: 'BOOKING_REQUEST',
  BOOKING_SUCCESS: 'BOOKING_SUCCESS',
  BOOKING_FAILURE: 'BOOKING_FAILURE',

  UNBOOK_REQUEST: 'UNBOOK_REQUEST',
  UNBOOK_SUCCESS: 'UNBOOK_SUCCESS',
  UNBOOK_FAILURE: 'UNBOOK_FAILURE',

  TOGGLE_ACTIVE: 'TOGGLE_ACTIVE',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
};

export const chatConstants = {
  ADD_MESSAGE: 'CHAT_ADD_MESSAGE',
};

export const creditCardConstants = {
  ADD_CARD: 'ADD_CARD',
  REMOVE_CARD: 'REMOVE_CARD',
  MAKE_CURRENT: 'MAKE_CURRENT',
};

export const ADD_CHECK = 'ADD_CHECK';
